<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23471" started-at="2021-07-08T11:32:41 EDT" finished-at="2021-07-08T11:33:04 EDT">
    <groups>
      <group name="SanityTest">
        <method signature="UPSTestRunner.loginErrorMessageTest()[pri:3, instance:ups.pack.UPSTestRunner@51e2adc7]" name="loginErrorMessageTest" class="ups.pack.UPSTestRunner"/>
        <method signature="UPSTestRunner.myDemoTest1()[pri:2, instance:ups.pack.UPSTestRunner@51e2adc7]" name="myDemoTest1" class="ups.pack.UPSTestRunner"/>
      </group> <!-- SanityTest -->
      <group name="RegressionTest">
        <method signature="UPSTestRunner.myDemoTest2()[pri:1, instance:ups.pack.UPSTestRunner@51e2adc7]" name="myDemoTest2" class="ups.pack.UPSTestRunner"/>
        <method signature="UPSTestRunner.signUpLinkTest()[pri:4, instance:ups.pack.UPSTestRunner@51e2adc7]" name="signUpLinkTest" class="ups.pack.UPSTestRunner"/>
      </group> <!-- RegressionTest -->
    </groups>
    <test name="Default test" duration-ms="23471" started-at="2021-07-08T11:32:41 EDT" finished-at="2021-07-08T11:33:04 EDT">
      <class name="ups.pack.UPSTestRunner">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="beforeMethod" is-config="true" duration-ms="1454" started-at="2021-07-08T11:32:41 EDT" finished-at="2021-07-08T11:32:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="myDemoTest2()[pri:1, instance:ups.pack.UPSTestRunner@51e2adc7]" name="myDemoTest2" duration-ms="5" started-at="2021-07-08T11:32:42 EDT" finished-at="2021-07-08T11:32:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myDemoTest2 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="afterMethod" is-config="true" duration-ms="59" started-at="2021-07-08T11:32:42 EDT" finished-at="2021-07-08T11:32:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="beforeMethod" is-config="true" duration-ms="1013" started-at="2021-07-08T11:32:42 EDT" finished-at="2021-07-08T11:32:43 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="upsSignUpPage()[pri:1, instance:ups.pack.UPSTestRunner@51e2adc7]" name="upsSignUpPage" duration-ms="2533" started-at="2021-07-08T11:32:43 EDT" finished-at="2021-07-08T11:32:46 EDT">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ups.pack.UPSTestRunner.upsSignUpPage(UPSTestRunner.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- upsSignUpPage -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="afterMethod" is-config="true" duration-ms="176" started-at="2021-07-08T11:32:46 EDT" finished-at="2021-07-08T11:32:46 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="beforeMethod" is-config="true" duration-ms="1089" started-at="2021-07-08T11:32:46 EDT" finished-at="2021-07-08T11:32:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="myDemoTest1()[pri:2, instance:ups.pack.UPSTestRunner@51e2adc7]" name="myDemoTest1" duration-ms="1" started-at="2021-07-08T11:32:47 EDT" finished-at="2021-07-08T11:32:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myDemoTest1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="afterMethod" is-config="true" duration-ms="67" started-at="2021-07-08T11:32:47 EDT" finished-at="2021-07-08T11:32:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="beforeMethod" is-config="true" duration-ms="1003" started-at="2021-07-08T11:32:47 EDT" finished-at="2021-07-08T11:32:48 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="loginErrorMessageTest()[pri:3, instance:ups.pack.UPSTestRunner@51e2adc7]" name="loginErrorMessageTest" duration-ms="5473" started-at="2021-07-08T11:32:48 EDT" finished-at="2021-07-08T11:32:54 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorMessageTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="afterMethod" is-config="true" duration-ms="4165" started-at="2021-07-08T11:32:54 EDT" finished-at="2021-07-08T11:32:58 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="beforeMethod" is-config="true" duration-ms="1086" started-at="2021-07-08T11:32:58 EDT" finished-at="2021-07-08T11:32:59 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="signUpLinkTest()[pri:4, instance:ups.pack.UPSTestRunner@51e2adc7]" name="signUpLinkTest" duration-ms="5154" started-at="2021-07-08T11:32:59 EDT" finished-at="2021-07-08T11:33:04 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign Up | UPS] but found [Sign up. | UPS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign Up | UPS] but found [Sign up. | UPS]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ups.pack.UPSTestRunner.signUpLinkTest(UPSTestRunner.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpLinkTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ups.pack.UPSTestRunner@51e2adc7]" name="afterMethod" is-config="true" duration-ms="164" started-at="2021-07-08T11:33:04 EDT" finished-at="2021-07-08T11:33:04 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- ups.pack.UPSTestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
